# Generated by Django 5.0.6 on 2024-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=70)),
                ('esal', models.FloatField()),
                ('econtact', models.BigIntegerField()),
                ('edeg', models.CharField(max_length=35)),
                ('eaddr', models.TextField()),
            ],
        ),
    ]
